title: "Deep Learning in NEXT"
tlink: "index.html"
description: ""
nextlink: "http://next.ific.uv.es/next"
github_username: "jerenner/next-deeplearning-analysis"
markdown: kramdown
theme: minima
gems: [jekyll-octicons]
pages: [Index]
